"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "english" | "hindi" | "tamil" | "telugu" | "bengali" | "marathi" | "gujarati" | "punjabi"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  english: {
    appName: "Farmers AI Assistant",
    home: "Home",
    diagnose: "Diagnose",
    history: "History",
    settings: "Settings",
    takePicture: "Take Picture",
    uploadImage: "Upload Image",
    diagnosisResults: "Diagnosis Results",
    treatments: "Treatments",
    organicTreatments: "Organic Treatments",
    chemicalTreatments: "Chemical Treatments",
    selectCrop: "Select Crop",
    selectLanguage: "Select Language",
    onlineMode: "Online Mode",
    offlineMode: "Offline Mode",
    loading: "Loading...",
    noResults: "No results found",
    viewHistory: "View History",
    logout: "Logout",
    login: "Login",
    register: "Register",
    welcomeMessage: "Diagnose plant diseases instantly with your camera",
    chat: "Chat",
    typeMessage: "Type a message...",
    sendMessage: "Send",
    recordAudio: "Record",
    stopRecording: "Stop",
    uploadImage: "Upload Image",
    chatWelcomeMessage: "Hello! I'm your farming assistant. How can I help you today?",
    stopSpeaking: "Stop Speaking",
    listen: "Listen",
    symptoms: "Symptoms",
    causes: "Causes",
    prevention: "Prevention",
    detectedCrop: "Detected Crop",
    analysisDetails: "Analysis Details",
    save: "Save",
    share: "Share",
    retakePhoto: "Retake Photo",
    analyzePlant: "Analyze Plant",
  },
  hindi: {
    appName: "किसान AI सहायक",
    home: "होम",
    diagnose: "निदान करें",
    history: "इतिहास",
    settings: "सेटिंग्स",
    takePicture: "तस्वीर लें",
    uploadImage: "छवि अपलोड करें",
    diagnosisResults: "निदान परिणाम",
    treatments: "उपचार",
    organicTreatments: "जैविक उपचार",
    chemicalTreatments: "रासायनिक उपचार",
    selectCrop: "फसल चुनें",
    selectLanguage: "भाषा चुनें",
    onlineMode: "ऑनलाइन मोड",
    offlineMode: "ऑफलाइन मोड",
    loading: "लोड हो रहा है...",
    noResults: "कोई परिणाम नहीं मिला",
    viewHistory: "इतिहास देखें",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "रजिस्टर",
    welcomeMessage: "अपने कैमरे से तुरंत पौधों के रोगों का निदान करें",
    chat: "चैट",
    typeMessage: "संदेश लिखें...",
    sendMessage: "भेजें",
    recordAudio: "रिकॉर्ड",
    stopRecording: "रोकें",
    uploadImage: "छवि अपलोड करें",
    chatWelcomeMessage: "नमस्ते! मैं आपका कृषि सहायक हूं। आज मैं आपकी कैसे मदद कर सकता हूं?",
    stopSpeaking: "बोलना बंद करें",
    listen: "सुनें",
    symptoms: "लक्षण",
    causes: "कारण",
    prevention: "रोकथाम",
    detectedCrop: "पहचानी गई फसल",
    analysisDetails: "विश्लेषण विवरण",
    save: "सहेजें",
    share: "साझा करें",
    retakePhoto: "फिर से फोटो लें",
    analyzePlant: "पौधे का विश्लेषण करें",
  },
  tamil: {
    appName: "விவசாயிகள் AI உதவியாளர்",
    home: "முகப்பு",
    diagnose: "நோயறிதல்",
    history: "வரலாறு",
    settings: "அமைப்புகள்",
    takePicture: "படம் எடுக்க",
    uploadImage: "படத்தை பதிவேற்றவும்",
    diagnosisResults: "நோயறிதல் முடிவுகள்",
    treatments: "சிகிச்சைகள்",
    organicTreatments: "இயற்கை சிகிச்சைகள்",
    chemicalTreatments: "இரசாயன சிகிச்சைகள்",
    selectCrop: "பயிரைத் தேர்ந்தெடுக்கவும்",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    onlineMode: "ஆன்லைன் முறை",
    offlineMode: "ஆஃப்லைன் முறை",
    loading: "ஏற்றுகிறது...",
    noResults: "முடிவுகள் எதுவும் இல்லை",
    viewHistory: "வரலாற்றைக் காண",
    logout: "வெளியேறு",
    login: "உள்நுழைய",
    register: "பதிவு செய்ய",
    welcomeMessage: "உங்கள் கேமராவுடன் உடனடியாக தாவர நோய்களை கண்டறியவும்",
    chat: "அரட்டை",
    typeMessage: "செய்தியை உள்ளிடவும்...",
    sendMessage: "அனுப்பு",
    recordAudio: "பதிவு",
    stopRecording: "நிறுத்து",
    uploadImage: "படத்தை பதிவேற்றவும்",
    chatWelcomeMessage: "வணக்கம்! நான் உங்கள் விவசாய உதவியாளர். இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    stopSpeaking: "பேசுவதை நிறுத்து",
    listen: "கேள்",
    symptoms: "அறிகுறிகள்",
    causes: "காரணங்கள்",
    prevention: "தடுப்பு",
    detectedCrop: "கண்டறியப்பட்ட பயிர்",
    analysisDetails: "பகுப்பாய்வு விவரங்கள்",
    save: "சேமி",
    share: "பகிர்",
    retakePhoto: "மீண்டும் புகைப்படம் எடுக்க",
    analyzePlant: "தாவரத்தை ஆராய்க",
  },
  telugu: {
    appName: "రైతుల AI సహాయకుడు",
    home: "హోమ్",
    diagnose: "రోగ నిర్ధారణ",
    history: "చరిత్ర",
    settings: "సెట్టింగులు",
    takePicture: "ఫోటో తీయండి",
    uploadImage: "చిత్రాన్ని అప్‌లోడ్ చేయండి",
    diagnosisResults: "రోగ నిర్ధారణ ఫలితాలు",
    treatments: "చికిత్సలు",
    organicTreatments: "సేంద్రీయ చికిత్సలు",
    chemicalTreatments: "రసాయన చికిత్సలు",
    selectCrop: "పంటను ఎంచుకోండి",
    selectLanguage: "భాషను ఎంచుకోండి",
    onlineMode: "ఆన్‌లైన్ మోడ్",
    offlineMode: "ఆఫ్‌లైన్ మోడ్",
    loading: "లోడ్ అవుతోంది...",
    noResults: "ఫలితాలు కనుగొనబడలేదు",
    viewHistory: "చరిత్రను వీక్షించండి",
    logout: "లాగౌట్",
    login: "లాగిన్",
    register: "నమోదు",
    welcomeMessage: "మీ కెమెరాతో వెంటనే మొక్కల వ్యాధులను గుర్తించండి",
    chat: "చాట్",
    typeMessage: "సందేశం రాయండి...",
    sendMessage: "పంపండి",
    recordAudio: "రికార్డ్",
    stopRecording: "ఆపు",
    uploadImage: "చిత్రాన్ని అప్‌లోడ్ చేయండి",
    chatWelcomeMessage: "హలో! నేను మీ వ్యవసాయ సహాయకుడిని. ఈ రోజు నేను మీకు ఎలా సహాయం చేయగలను?",
    stopSpeaking: "మాట్లాడటం ఆపు",
    listen: "వినండి",
    symptoms: "లక్షణాలు",
    causes: "కారణాలు",
    prevention: "నివారణ",
    detectedCrop: "గుర్తించబడిన పంట",
    analysisDetails: "విశ్లేషణ వివరాలు",
    save: "సేవ్ చేయండి",
    share: "షేర్ చేయండి",
    retakePhoto: "మళ్ళీ ఫోటో తీయండి",
    analyzePlant: "మొక్కను విశ్లేషించండి",
  },
  bengali: {
    appName: "কৃষক AI সহকারী",
    home: "হোম",
    diagnose: "রোগ নির্ণয়",
    history: "ইতিহাস",
    settings: "সেটিংস",
    takePicture: "ছবি তুলুন",
    uploadImage: "ছবি আপলোড করুন",
    diagnosisResults: "রোগ নির্ণয়ের ফলাফল",
    treatments: "চিকিৎসা",
    organicTreatments: "জৈব চিকিৎসা",
    chemicalTreatments: "রাসায়নিক চিকিৎসা",
    selectCrop: "ফসল নির্বাচন করুন",
    selectLanguage: "ভাষা নির্বাচন করুন",
    onlineMode: "অনলাইন মোড",
    offlineMode: "অফলাইন মোড",
    loading: "লোড হচ্ছে...",
    noResults: "কোন ফলাফল পাওয়া যায়নি",
    viewHistory: "ইতিহাস দেখুন",
    logout: "লগআউট",
    login: "লগইন",
    register: "নিবন্ধন",
    welcomeMessage: "আপনার ক্যামেরা দিয়ে তাৎক্ষণিকভাবে উদ্ভিদের রোগ নির্ণয় করুন",
    chat: "চ্যাট",
    typeMessage: "একটি বার্তা লিখুন...",
    sendMessage: "প্রেরণ",
    recordAudio: "রেকর্ড",
    stopRecording: "থামুন",
    uploadImage: "ছবি আপলোড করুন",
    chatWelcomeMessage: "হ্যালো! আমি আপনার কৃষি সহকারী। আমি আজ আপনাকে কিভাবে সাহায্য করতে পারি?",
    stopSpeaking: "কথা বলা বন্ধ করুন",
    listen: "শুনুন",
    symptoms: "লক্ষণগুলি",
    causes: "কারণগুলি",
    prevention: "প্রতিরোধ",
    detectedCrop: "শনাক্ত করা ফসল",
    analysisDetails: "বিশ্লেষণের বিবরণ",
    save: "সংরক্ষণ করুন",
    share: "শেয়ার করুন",
    retakePhoto: "আবার ছবি তুলুন",
    analyzePlant: "উদ্ভিদ বিশ্লেষণ করুন",
  },
  marathi: {
    appName: "शेतकरी AI सहाय्यक",
    home: "होम",
    diagnose: "निदान",
    history: "इतिहास",
    settings: "सेटिंग्ज",
    takePicture: "फोटो काढा",
    uploadImage: "प्रतिमा अपलोड करा",
    diagnosisResults: "निदान परिणाम",
    treatments: "उपचार",
    organicTreatments: "सेंद्रिय उपचार",
    chemicalTreatments: "रासायनिक उपचार",
    selectCrop: "पीक निवडा",
    selectLanguage: "भाषा निवडा",
    onlineMode: "ऑनलाइन मोड",
    offlineMode: "ऑफलाइन मोड",
    loading: "लोड होत आहे...",
    noResults: "कोणतेही परिणाम सापडले नाहीत",
    viewHistory: "इतिहास पहा",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "नोंदणी",
    welcomeMessage: "आपल्या कॅमेऱ्याने त्वरित वनस्पतींच्या रोगांचे निदान करा",
    chat: "चॅट",
    typeMessage: "संदेश लिहा...",
    sendMessage: "पाठवा",
    recordAudio: "रेकॉर्ड",
    stopRecording: "थांबा",
    uploadImage: "प्रतिमा अपलोड करा",
    chatWelcomeMessage: "नमस्कार! मी तुमचा कृषी सहाय्यक आहे. मी आज तुम्हाला कशी मदत करू शकतो?",
    stopSpeaking: "बोलणे थांबवा",
    listen: "ऐका",
    symptoms: "लक्षणे",
    causes: "कारणे",
    prevention: "प्रतिबंध",
    detectedCrop: "शोधलेले पीक",
    analysisDetails: "विश्लेषण तपशील",
    save: "जतन करा",
    share: "शेअर करा",
    retakePhoto: "पुन्हा फोटो काढा",
    analyzePlant: "वनस्पतीचे विश्लेषण करा",
  },
  gujarati: {
    appName: "ખેડૂત AI સહાયક",
    home: "હોમ",
    diagnose: "નિદાન",
    history: "ઇતિહાસ",
    settings: "સેટિંગ્સ",
    takePicture: "ફોટો લો",
    uploadImage: "છબી અપલોડ કરો",
    diagnosisResults: "નિદાન પરિણામો",
    treatments: "સારવાર",
    organicTreatments: "જૈવિક સારવાર",
    chemicalTreatments: "રાસાયણિક સારવાર",
    selectCrop: "પાક પસંદ કરો",
    selectLanguage: "ભાષા પસંદ કરો",
    onlineMode: "ઓનલાઇન મોડ",
    offlineMode: "ઓફલાઇન મોડ",
    loading: "લોડ થઈ રહ્યું છે...",
    noResults: "કોઈ પરિણામ મળ્યું નથી",
    viewHistory: "ઇતિહાસ જુઓ",
    logout: "લૉગઆઉટ",
    login: "લૉગિન",
    register: "નોંધણી",
    welcomeMessage: "તમારા કેમેરા સાથે તરત જ વનસ્પતિના રોગોનું નિદાન કરો",
    chat: "ચેટ",
    typeMessage: "સંદેશ લખો...",
    sendMessage: "મોકલો",
    recordAudio: "રેકોર્ડ",
    stopRecording: "બંધ કરો",
    uploadImage: "છબી અપલોડ કરો",
    chatWelcomeMessage: "નમસ્તે! હું તમારો કૃષિ સહાયક છું. હું આજે તમને કેવી રીતે મદદ કરી શકું?",
    stopSpeaking: "બોલવાનું બંધ કરો",
    listen: "સાંભળો",
    symptoms: "લક્ષણો",
    causes: "કારણો",
    prevention: "નિવારણ",
    detectedCrop: "શોધાયેલ પાક",
    analysisDetails: "વિશ્લેષણ વિગતો",
    save: "સાચવો",
    share: "શેર કરો",
    retakePhoto: "ફરીથી ફોટો લો",
    analyzePlant: "છોડનું વિશ્લેષણ કરો",
  },
  punjabi: {
    appName: "ਕਿਸਾਨ AI ਸਹਾਇਕ",
    home: "ਹੋਮ",
    diagnose: "ਰੋਗ ਦਾ ਪਤਾ ਲਗਾਓ",
    history: "ਇਤਿਹਾਸ",
    settings: "ਸੈਟਿੰਗਾਂ",
    takePicture: "ਤਸਵੀਰ ਲਓ",
    uploadImage: "ਚਿੱਤਰ ਅਪਲੋਡ ਕਰੋ",
    diagnosisResults: "ਰੋਗ ਦੇ ਨਤੀਜੇ",
    treatments: "ਇਲਾਜ",
    organicTreatments: "ਜੈਵਿਕ ਇਲਾਜ",
    chemicalTreatments: "ਰਸਾਇਣਕ ਇਲਾਜ",
    selectCrop: "ਫਸਲ ਚੁਣੋ",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    onlineMode: "ਔਨਲਾਈਨ ਮੋਡ",
    offlineMode: "ਔਫਲਾਈਨ ਮੋਡ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    noResults: "ਕੋਈ ਨਤੀਜੇ ਨਹੀਂ ਮਿਲੇ",
    viewHistory: "ਇਤਿਹਾਸ ਵੇਖੋ",
    logout: "ਲੌਗਆਊਟ",
    login: "ਲੌਗਇਨ",
    register: "ਰਜਿਸਟਰ",
    welcomeMessage: "ਆਪਣੇ ਕੈਮਰੇ ਨਾਲ ਤੁਰੰਤ ਪੌਦਿਆਂ ਦੀਆਂ ਬਿਮਾਰੀਆਂ ਦਾ ਪਤਾ ਲਗਾਓ",
    chat: "ਚੈਟ",
    typeMessage: "ਇੱਕ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...",
    sendMessage: "ਭੇਜੋ",
    recordAudio: "ਰਿਕਾਰਡ",
    stopRecording: "ਬੰਦ ਕਰੋ",
    uploadImage: "ਚਿੱਤਰ ਅਪਲੋਡ ਕਰੋ",
    chatWelcomeMessage: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਡਾ ਖੇਤੀਬਾੜੀ ਸਹਾਇਕ ਹਾਂ। ਮੈਂ ਅੱਜ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?",
    stopSpeaking: "ਬੋਲਣਾ ਬੰਦ ਕਰੋ",
    listen: "ਸੁਣੋ",
    symptoms: "ਲੱਛਣ",
    causes: "ਕਾਰਨ",
    prevention: "ਰੋਕਥਾਮ",
    detectedCrop: "ਪਛਾਣੀ ਗਈ ਫਸਲ",
    analysisDetails: "ਵਿਸ਼ਲੇਸ਼ਣ ਵੇਰਵੇ",
    save: "ਸੰਭਾਲੋ",
    share: "ਸਾਂਝਾ ਕਰੋ",
    retakePhoto: "ਦੁਬਾਰਾ ਫੋਟੋ ਲਓ",
    analyzePlant: "ਪੌਦੇ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: "english",
  setLanguage: () => {},
  t: (key: string) => key,
})

export const useLanguage = () => useContext(LanguageContext)

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>("english")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}
